# Makefile.in generated by automake 1.14.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2013 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



# Makefile.am par Mael Valais - 2014
# Nécessaire à automake

# Ce fichier contient les noms des fichiers qui permettent la compilation Autotools

# Les fichiers Makefile.am (vides) dans tous les sous-dossiers sont obligatoires mais
# j'ai décidé de tout mettre dans celui-ci pour simplifier (grâce à subdir-objects dans 
# configure.ac)

# CONCERNANT Qt (à travers autotroll.m4 et autotroll.mk) : 
# - include autotroll.mk permet d'ajouter les règles implicites pour compiler 
#		les .ui en _ui.h, les .moc en .moc.cpp...
# - BUILT_SOURCES= contient tous les fichiers .ui ou .moc ou .rcc qui devront être
# 		compilés par les outils uic, moc ou rcc. Si on met mainwindow_ui.h dans
#		prog_SOURCES par exemple, il faudra qu'on écrive : 
#		BUILT_SOURCES=mainwindow_ui.h

# Makerules.
# This file is part of AutoTroll.
# Copyright (C) 2006  Benoit Sigoure.
#
# AutoTroll is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301,
# USA.


am__is_gnu_make = test -n '$(MAKEFILE_LIST)' && test -n '$(MAKELEVEL)'
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/climso-auto
pkgincludedir = $(includedir)/climso-auto
pkglibdir = $(libdir)/climso-auto
pkglibexecdir = $(libexecdir)/climso-auto
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-apple-darwin13.2.0
host_triplet = x86_64-apple-darwin13.2.0
DIST_COMMON = $(srcdir)/autotroll.mk $(srcdir)/Makefile.in \
	$(srcdir)/Makefile.am $(top_srcdir)/configure \
	$(am__configure_deps) $(srcdir)/config.h.in \
	$(top_srcdir)/config/depcomp config/compile \
	config/config.guess config/config.sub config/depcomp \
	config/install-sh config/missing $(top_srcdir)/config/compile \
	$(top_srcdir)/config/config.guess \
	$(top_srcdir)/config/config.sub \
	$(top_srcdir)/config/install-sh $(top_srcdir)/config/missing
bin_PROGRAMS = test_classe_image$(EXEEXT)
subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/m4/check_framework.m4 \
	$(top_srcdir)/m4/autotroll.m4 $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)"
PROGRAMS = $(bin_PROGRAMS)
am__dirstamp = $(am__leading_dot)dirstamp
am_test_classe_image_OBJECTS =  \
	src/test_classe_image-main_image.$(OBJEXT) \
	src/test_classe_image-cmd_arduino.$(OBJEXT) \
	src/test_classe_image-interpol.$(OBJEXT) \
	src/test_classe_image-csbigcam.$(OBJEXT) \
	src/test_classe_image-csbigimg.$(OBJEXT) \
	src/test_classe_image-diametre_soleil.$(OBJEXT) \
	src/test_classe_image-exceptions.$(OBJEXT) \
	src/test_classe_image-image.$(OBJEXT)
test_classe_image_OBJECTS = $(am_test_classe_image_OBJECTS)
am__DEPENDENCIES_1 =
test_classe_image_DEPENDENCIES = $(am__DEPENDENCIES_1)
test_classe_image_LINK = $(CXXLD) $(test_classe_image_CXXFLAGS) \
	$(CXXFLAGS) $(test_classe_image_LDFLAGS) $(LDFLAGS) -o $@
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/config/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
am__v_lt_1 = 
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC      " $@;
am__v_CC_1 = 
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD    " $@;
am__v_CCLD_1 = 
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
AM_V_CXX = $(am__v_CXX_$(V))
am__v_CXX_ = $(am__v_CXX_$(AM_DEFAULT_VERBOSITY))
am__v_CXX_0 = @echo "  CXX     " $@;
am__v_CXX_1 = 
CXXLD = $(CXX)
CXXLINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) \
	-o $@
AM_V_CXXLD = $(am__v_CXXLD_$(V))
am__v_CXXLD_ = $(am__v_CXXLD_$(AM_DEFAULT_VERBOSITY))
am__v_CXXLD_0 = @echo "  CXXLD   " $@;
am__v_CXXLD_1 = 
SOURCES = $(test_classe_image_SOURCES)
DIST_SOURCES = $(test_classe_image_SOURCES)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) \
	$(LISP)config.h.in
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
CSCOPE = cscope
AM_RECURSIVE_TARGETS = cscope
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
DIST_TARGETS = dist-gzip
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /Users/mael65/prog/climso-auto/config/missing aclocal-1.14
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 1
AUTOCONF = ${SHELL} /Users/mael65/prog/climso-auto/config/missing autoconf
AUTOHEADER = ${SHELL} /Users/mael65/prog/climso-auto/config/missing autoheader
AUTOMAKE = ${SHELL} /Users/mael65/prog/climso-auto/config/missing automake-1.14
AWK = awk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g --pedantic -Wall -std=c99 -O2
CPP = gcc -E
CPPFLAGS = 
CXX = g++
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
ECHO_C = \c
ECHO_N = 
ECHO_T = 
EGREP = /usr/bin/grep -E
EXEEXT = 
FRAMEWORK_SBIGUDRV = -framework sbigudrv
GREP = /usr/bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBOBJS =  ${LIBOBJDIR}mktime$U.o
LIBS = -ltiff -lm  -framework sbigudrv
LTLIBOBJS =  ${LIBOBJDIR}mktime$U.lo
MAKEINFO = ${SHELL} /Users/mael65/prog/climso-auto/config/missing makeinfo
MKDIR_P = config/install-sh -c -d
MOC = /usr/local/bin/moc
OBJEXT = o
PACKAGE = climso-auto
PACKAGE_BUGREPORT = mael.valais@irap.omp.eu
PACKAGE_NAME = climso-auto
PACKAGE_STRING = climso-auto 1.0
PACKAGE_TARNAME = climso-auto
PACKAGE_URL = 
PACKAGE_VERSION = 1.0
PATH_SEPARATOR = :
QMAKE = /usr/local/bin/qmake
QT_CFLAGS = -pipe -mmacosx-version-min=10.7 -O2 -arch x86_64 -Wall -W $(QT_DEFINES)
QT_CPPFLAGS = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/local/Cellar/qt/4.8.5/mkspecs/unsupported/macx-clang-libc++ -I. -I/usr/local/Cellar/qt/4.8.5/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.5/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.5/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.5/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.5/include -I. -I. -F/usr/local/Cellar/qt/4.8.5/lib
QT_CXXFLAGS = -pipe -stdlib=libc++ -mmacosx-version-min=10.7 -O2 -arch x86_64 -Wall -W $(QT_DEFINES)
QT_DEFINES = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
QT_INCPATH = -I/usr/local/Cellar/qt/4.8.5/mkspecs/unsupported/macx-clang-libc++ -I. -I/usr/local/Cellar/qt/4.8.5/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.5/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.5/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.5/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.5/include -I. -I. -F/usr/local/Cellar/qt/4.8.5/lib
QT_LDFLAGS = -headerpad_max_install_names -stdlib=libc++ -mmacosx-version-min=10.7 -arch x86_64
QT_LFLAGS = -headerpad_max_install_names -stdlib=libc++ -mmacosx-version-min=10.7 -arch x86_64
QT_LIBS = -Wl,-F/usr/local/Cellar/qt/4.8.5/lib -L/usr/local/Cellar/qt/4.8.5/lib -framework QtGui -L/opt/X11/lib -L/usr/local/Cellar/qt/4.8.5/lib -Wl,-F/usr/local/Cellar/qt/4.8.5/lib -framework QtCore 
QT_PATH = /usr/local/bin
QT_VERSION_MAJOR = ok, looks like Qt 4
RCC = /usr/local/bin/rcc
SET_MAKE = 
SHELL = /bin/sh
STRIP = 
TMPDIR = /var/folders/8f/mmpn479168g_rtnr15z__0jh0000gn/T/
UIC = /usr/local/bin/uic
VERSION = 1.0
abs_builddir = /Users/mael65/prog/climso-auto
abs_srcdir = /Users/mael65/prog/climso-auto
abs_top_builddir = /Users/mael65/prog/climso-auto
abs_top_srcdir = /Users/mael65/prog/climso-auto
ac_ct_CC = gcc
ac_ct_CXX = g++
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build = x86_64-apple-darwin13.2.0
build_alias = 
build_cpu = x86_64
build_os = darwin13.2.0
build_vendor = apple
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = x86_64-apple-darwin13.2.0
host_alias = 
host_cpu = x86_64
host_os = darwin13.2.0
host_vendor = apple
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /Users/mael65/prog/climso-auto/config/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .

# See autotroll.m4 :)

#NOTE MV: Il s'agit de règles implicites avec double suffixe
# .ui.ui.h: signifie %.ui: %.ui.h
SUFFIXES = .moc.cpp .moc.cc .moc.cxx .moc.C .h .hh \
           .ui .ui.h .ui.hh \
           .qrc .qrc.cpp .qrc.cc .qrc.cxx .qrc.C

DISTCLEANFILES = $(BUILT_SOURCES)

# Appel au makefile pour les moc, uic, rcc 
# provenant de autotroll

# Pour que aclocal puisse trouver les fichiers .m4
ACLOCAL_AMFLAGS = -I m4
test_classe_image_SOURCES = \
	src/main_image.cpp\
	src/cmd_arduino.c\
	src/interpol.c\
	src/csbigcam.cpp src/csbigimg.cpp src/diametre_soleil.c\
  	src/exceptions.cpp  src/image.cpp

#test_classe_image_HEADERS=
#	src/mainwindow.ui
test_classe_image_CXXFLAGS = $(QT_CXXFLAGS) $(AM_CXXFLAGS)
test_classe_image_CPPFLAGS = $(QT_CPPFLAGS) $(AM_CPPFLAGS) -DDEBUG
test_classe_image_LDFLAGS = $(QT_LDFLAGS) $(LDFLAGS)
test_classe_image_LDADD = $(QT_LIBS) $(LDADD)

# Fichiers qui devront être compilés par uic ou moc avant la compilation
# Voir CONCERNANT Qt au dessus
BUILT_SOURCES = 
all: $(BUILT_SOURCES) config.h
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .moc.cpp .moc.cc .moc.cxx .moc.C .h .hh .ui .ui.h .ui.hh .qrc .qrc.cpp .qrc.cc .qrc.cxx .qrc.C .c .cpp .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am $(srcdir)/autotroll.mk $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;
$(srcdir)/autotroll.mk:

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

config.h: stamp-h1
	@test -f $@ || rm -f stamp-h1
	@test -f $@ || $(MAKE) $(AM_MAKEFLAGS) stamp-h1

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p \
	  ; then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' \
	    -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' \
	`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
src/$(am__dirstamp):
	@$(MKDIR_P) src
	@: > src/$(am__dirstamp)
src/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/$(DEPDIR)
	@: > src/$(DEPDIR)/$(am__dirstamp)
src/test_classe_image-main_image.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/test_classe_image-cmd_arduino.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/test_classe_image-interpol.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/test_classe_image-csbigcam.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/test_classe_image-csbigimg.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/test_classe_image-diametre_soleil.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/test_classe_image-exceptions.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/test_classe_image-image.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)

test_classe_image$(EXEEXT): $(test_classe_image_OBJECTS) $(test_classe_image_DEPENDENCIES) $(EXTRA_test_classe_image_DEPENDENCIES) 
	@rm -f test_classe_image$(EXEEXT)
	$(AM_V_CXXLD)$(test_classe_image_LINK) $(test_classe_image_OBJECTS) $(test_classe_image_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f src/*.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include src/$(DEPDIR)/test_classe_image-cmd_arduino.Po
include src/$(DEPDIR)/test_classe_image-csbigcam.Po
include src/$(DEPDIR)/test_classe_image-csbigimg.Po
include src/$(DEPDIR)/test_classe_image-diametre_soleil.Po
include src/$(DEPDIR)/test_classe_image-exceptions.Po
include src/$(DEPDIR)/test_classe_image-image.Po
include src/$(DEPDIR)/test_classe_image-interpol.Po
include src/$(DEPDIR)/test_classe_image-main_image.Po

.c.o:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ $<

.c.obj:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

src/test_classe_image-cmd_arduino.o: src/cmd_arduino.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_classe_image_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/test_classe_image-cmd_arduino.o -MD -MP -MF src/$(DEPDIR)/test_classe_image-cmd_arduino.Tpo -c -o src/test_classe_image-cmd_arduino.o `test -f 'src/cmd_arduino.c' || echo '$(srcdir)/'`src/cmd_arduino.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/test_classe_image-cmd_arduino.Tpo src/$(DEPDIR)/test_classe_image-cmd_arduino.Po
#	$(AM_V_CC)source='src/cmd_arduino.c' object='src/test_classe_image-cmd_arduino.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_classe_image_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/test_classe_image-cmd_arduino.o `test -f 'src/cmd_arduino.c' || echo '$(srcdir)/'`src/cmd_arduino.c

src/test_classe_image-cmd_arduino.obj: src/cmd_arduino.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_classe_image_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/test_classe_image-cmd_arduino.obj -MD -MP -MF src/$(DEPDIR)/test_classe_image-cmd_arduino.Tpo -c -o src/test_classe_image-cmd_arduino.obj `if test -f 'src/cmd_arduino.c'; then $(CYGPATH_W) 'src/cmd_arduino.c'; else $(CYGPATH_W) '$(srcdir)/src/cmd_arduino.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/test_classe_image-cmd_arduino.Tpo src/$(DEPDIR)/test_classe_image-cmd_arduino.Po
#	$(AM_V_CC)source='src/cmd_arduino.c' object='src/test_classe_image-cmd_arduino.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_classe_image_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/test_classe_image-cmd_arduino.obj `if test -f 'src/cmd_arduino.c'; then $(CYGPATH_W) 'src/cmd_arduino.c'; else $(CYGPATH_W) '$(srcdir)/src/cmd_arduino.c'; fi`

src/test_classe_image-interpol.o: src/interpol.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_classe_image_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/test_classe_image-interpol.o -MD -MP -MF src/$(DEPDIR)/test_classe_image-interpol.Tpo -c -o src/test_classe_image-interpol.o `test -f 'src/interpol.c' || echo '$(srcdir)/'`src/interpol.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/test_classe_image-interpol.Tpo src/$(DEPDIR)/test_classe_image-interpol.Po
#	$(AM_V_CC)source='src/interpol.c' object='src/test_classe_image-interpol.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_classe_image_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/test_classe_image-interpol.o `test -f 'src/interpol.c' || echo '$(srcdir)/'`src/interpol.c

src/test_classe_image-interpol.obj: src/interpol.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_classe_image_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/test_classe_image-interpol.obj -MD -MP -MF src/$(DEPDIR)/test_classe_image-interpol.Tpo -c -o src/test_classe_image-interpol.obj `if test -f 'src/interpol.c'; then $(CYGPATH_W) 'src/interpol.c'; else $(CYGPATH_W) '$(srcdir)/src/interpol.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/test_classe_image-interpol.Tpo src/$(DEPDIR)/test_classe_image-interpol.Po
#	$(AM_V_CC)source='src/interpol.c' object='src/test_classe_image-interpol.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_classe_image_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/test_classe_image-interpol.obj `if test -f 'src/interpol.c'; then $(CYGPATH_W) 'src/interpol.c'; else $(CYGPATH_W) '$(srcdir)/src/interpol.c'; fi`

src/test_classe_image-diametre_soleil.o: src/diametre_soleil.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_classe_image_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/test_classe_image-diametre_soleil.o -MD -MP -MF src/$(DEPDIR)/test_classe_image-diametre_soleil.Tpo -c -o src/test_classe_image-diametre_soleil.o `test -f 'src/diametre_soleil.c' || echo '$(srcdir)/'`src/diametre_soleil.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/test_classe_image-diametre_soleil.Tpo src/$(DEPDIR)/test_classe_image-diametre_soleil.Po
#	$(AM_V_CC)source='src/diametre_soleil.c' object='src/test_classe_image-diametre_soleil.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_classe_image_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/test_classe_image-diametre_soleil.o `test -f 'src/diametre_soleil.c' || echo '$(srcdir)/'`src/diametre_soleil.c

src/test_classe_image-diametre_soleil.obj: src/diametre_soleil.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_classe_image_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/test_classe_image-diametre_soleil.obj -MD -MP -MF src/$(DEPDIR)/test_classe_image-diametre_soleil.Tpo -c -o src/test_classe_image-diametre_soleil.obj `if test -f 'src/diametre_soleil.c'; then $(CYGPATH_W) 'src/diametre_soleil.c'; else $(CYGPATH_W) '$(srcdir)/src/diametre_soleil.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/test_classe_image-diametre_soleil.Tpo src/$(DEPDIR)/test_classe_image-diametre_soleil.Po
#	$(AM_V_CC)source='src/diametre_soleil.c' object='src/test_classe_image-diametre_soleil.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_classe_image_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/test_classe_image-diametre_soleil.obj `if test -f 'src/diametre_soleil.c'; then $(CYGPATH_W) 'src/diametre_soleil.c'; else $(CYGPATH_W) '$(srcdir)/src/diametre_soleil.c'; fi`

.cpp.o:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ $<

.cpp.obj:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

src/test_classe_image-main_image.o: src/main_image.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_classe_image_CPPFLAGS) $(CPPFLAGS) $(test_classe_image_CXXFLAGS) $(CXXFLAGS) -MT src/test_classe_image-main_image.o -MD -MP -MF src/$(DEPDIR)/test_classe_image-main_image.Tpo -c -o src/test_classe_image-main_image.o `test -f 'src/main_image.cpp' || echo '$(srcdir)/'`src/main_image.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/test_classe_image-main_image.Tpo src/$(DEPDIR)/test_classe_image-main_image.Po
#	$(AM_V_CXX)source='src/main_image.cpp' object='src/test_classe_image-main_image.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_classe_image_CPPFLAGS) $(CPPFLAGS) $(test_classe_image_CXXFLAGS) $(CXXFLAGS) -c -o src/test_classe_image-main_image.o `test -f 'src/main_image.cpp' || echo '$(srcdir)/'`src/main_image.cpp

src/test_classe_image-main_image.obj: src/main_image.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_classe_image_CPPFLAGS) $(CPPFLAGS) $(test_classe_image_CXXFLAGS) $(CXXFLAGS) -MT src/test_classe_image-main_image.obj -MD -MP -MF src/$(DEPDIR)/test_classe_image-main_image.Tpo -c -o src/test_classe_image-main_image.obj `if test -f 'src/main_image.cpp'; then $(CYGPATH_W) 'src/main_image.cpp'; else $(CYGPATH_W) '$(srcdir)/src/main_image.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/test_classe_image-main_image.Tpo src/$(DEPDIR)/test_classe_image-main_image.Po
#	$(AM_V_CXX)source='src/main_image.cpp' object='src/test_classe_image-main_image.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_classe_image_CPPFLAGS) $(CPPFLAGS) $(test_classe_image_CXXFLAGS) $(CXXFLAGS) -c -o src/test_classe_image-main_image.obj `if test -f 'src/main_image.cpp'; then $(CYGPATH_W) 'src/main_image.cpp'; else $(CYGPATH_W) '$(srcdir)/src/main_image.cpp'; fi`

src/test_classe_image-csbigcam.o: src/csbigcam.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_classe_image_CPPFLAGS) $(CPPFLAGS) $(test_classe_image_CXXFLAGS) $(CXXFLAGS) -MT src/test_classe_image-csbigcam.o -MD -MP -MF src/$(DEPDIR)/test_classe_image-csbigcam.Tpo -c -o src/test_classe_image-csbigcam.o `test -f 'src/csbigcam.cpp' || echo '$(srcdir)/'`src/csbigcam.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/test_classe_image-csbigcam.Tpo src/$(DEPDIR)/test_classe_image-csbigcam.Po
#	$(AM_V_CXX)source='src/csbigcam.cpp' object='src/test_classe_image-csbigcam.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_classe_image_CPPFLAGS) $(CPPFLAGS) $(test_classe_image_CXXFLAGS) $(CXXFLAGS) -c -o src/test_classe_image-csbigcam.o `test -f 'src/csbigcam.cpp' || echo '$(srcdir)/'`src/csbigcam.cpp

src/test_classe_image-csbigcam.obj: src/csbigcam.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_classe_image_CPPFLAGS) $(CPPFLAGS) $(test_classe_image_CXXFLAGS) $(CXXFLAGS) -MT src/test_classe_image-csbigcam.obj -MD -MP -MF src/$(DEPDIR)/test_classe_image-csbigcam.Tpo -c -o src/test_classe_image-csbigcam.obj `if test -f 'src/csbigcam.cpp'; then $(CYGPATH_W) 'src/csbigcam.cpp'; else $(CYGPATH_W) '$(srcdir)/src/csbigcam.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/test_classe_image-csbigcam.Tpo src/$(DEPDIR)/test_classe_image-csbigcam.Po
#	$(AM_V_CXX)source='src/csbigcam.cpp' object='src/test_classe_image-csbigcam.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_classe_image_CPPFLAGS) $(CPPFLAGS) $(test_classe_image_CXXFLAGS) $(CXXFLAGS) -c -o src/test_classe_image-csbigcam.obj `if test -f 'src/csbigcam.cpp'; then $(CYGPATH_W) 'src/csbigcam.cpp'; else $(CYGPATH_W) '$(srcdir)/src/csbigcam.cpp'; fi`

src/test_classe_image-csbigimg.o: src/csbigimg.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_classe_image_CPPFLAGS) $(CPPFLAGS) $(test_classe_image_CXXFLAGS) $(CXXFLAGS) -MT src/test_classe_image-csbigimg.o -MD -MP -MF src/$(DEPDIR)/test_classe_image-csbigimg.Tpo -c -o src/test_classe_image-csbigimg.o `test -f 'src/csbigimg.cpp' || echo '$(srcdir)/'`src/csbigimg.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/test_classe_image-csbigimg.Tpo src/$(DEPDIR)/test_classe_image-csbigimg.Po
#	$(AM_V_CXX)source='src/csbigimg.cpp' object='src/test_classe_image-csbigimg.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_classe_image_CPPFLAGS) $(CPPFLAGS) $(test_classe_image_CXXFLAGS) $(CXXFLAGS) -c -o src/test_classe_image-csbigimg.o `test -f 'src/csbigimg.cpp' || echo '$(srcdir)/'`src/csbigimg.cpp

src/test_classe_image-csbigimg.obj: src/csbigimg.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_classe_image_CPPFLAGS) $(CPPFLAGS) $(test_classe_image_CXXFLAGS) $(CXXFLAGS) -MT src/test_classe_image-csbigimg.obj -MD -MP -MF src/$(DEPDIR)/test_classe_image-csbigimg.Tpo -c -o src/test_classe_image-csbigimg.obj `if test -f 'src/csbigimg.cpp'; then $(CYGPATH_W) 'src/csbigimg.cpp'; else $(CYGPATH_W) '$(srcdir)/src/csbigimg.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/test_classe_image-csbigimg.Tpo src/$(DEPDIR)/test_classe_image-csbigimg.Po
#	$(AM_V_CXX)source='src/csbigimg.cpp' object='src/test_classe_image-csbigimg.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_classe_image_CPPFLAGS) $(CPPFLAGS) $(test_classe_image_CXXFLAGS) $(CXXFLAGS) -c -o src/test_classe_image-csbigimg.obj `if test -f 'src/csbigimg.cpp'; then $(CYGPATH_W) 'src/csbigimg.cpp'; else $(CYGPATH_W) '$(srcdir)/src/csbigimg.cpp'; fi`

src/test_classe_image-exceptions.o: src/exceptions.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_classe_image_CPPFLAGS) $(CPPFLAGS) $(test_classe_image_CXXFLAGS) $(CXXFLAGS) -MT src/test_classe_image-exceptions.o -MD -MP -MF src/$(DEPDIR)/test_classe_image-exceptions.Tpo -c -o src/test_classe_image-exceptions.o `test -f 'src/exceptions.cpp' || echo '$(srcdir)/'`src/exceptions.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/test_classe_image-exceptions.Tpo src/$(DEPDIR)/test_classe_image-exceptions.Po
#	$(AM_V_CXX)source='src/exceptions.cpp' object='src/test_classe_image-exceptions.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_classe_image_CPPFLAGS) $(CPPFLAGS) $(test_classe_image_CXXFLAGS) $(CXXFLAGS) -c -o src/test_classe_image-exceptions.o `test -f 'src/exceptions.cpp' || echo '$(srcdir)/'`src/exceptions.cpp

src/test_classe_image-exceptions.obj: src/exceptions.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_classe_image_CPPFLAGS) $(CPPFLAGS) $(test_classe_image_CXXFLAGS) $(CXXFLAGS) -MT src/test_classe_image-exceptions.obj -MD -MP -MF src/$(DEPDIR)/test_classe_image-exceptions.Tpo -c -o src/test_classe_image-exceptions.obj `if test -f 'src/exceptions.cpp'; then $(CYGPATH_W) 'src/exceptions.cpp'; else $(CYGPATH_W) '$(srcdir)/src/exceptions.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/test_classe_image-exceptions.Tpo src/$(DEPDIR)/test_classe_image-exceptions.Po
#	$(AM_V_CXX)source='src/exceptions.cpp' object='src/test_classe_image-exceptions.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_classe_image_CPPFLAGS) $(CPPFLAGS) $(test_classe_image_CXXFLAGS) $(CXXFLAGS) -c -o src/test_classe_image-exceptions.obj `if test -f 'src/exceptions.cpp'; then $(CYGPATH_W) 'src/exceptions.cpp'; else $(CYGPATH_W) '$(srcdir)/src/exceptions.cpp'; fi`

src/test_classe_image-image.o: src/image.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_classe_image_CPPFLAGS) $(CPPFLAGS) $(test_classe_image_CXXFLAGS) $(CXXFLAGS) -MT src/test_classe_image-image.o -MD -MP -MF src/$(DEPDIR)/test_classe_image-image.Tpo -c -o src/test_classe_image-image.o `test -f 'src/image.cpp' || echo '$(srcdir)/'`src/image.cpp
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/test_classe_image-image.Tpo src/$(DEPDIR)/test_classe_image-image.Po
#	$(AM_V_CXX)source='src/image.cpp' object='src/test_classe_image-image.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_classe_image_CPPFLAGS) $(CPPFLAGS) $(test_classe_image_CXXFLAGS) $(CXXFLAGS) -c -o src/test_classe_image-image.o `test -f 'src/image.cpp' || echo '$(srcdir)/'`src/image.cpp

src/test_classe_image-image.obj: src/image.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_classe_image_CPPFLAGS) $(CPPFLAGS) $(test_classe_image_CXXFLAGS) $(CXXFLAGS) -MT src/test_classe_image-image.obj -MD -MP -MF src/$(DEPDIR)/test_classe_image-image.Tpo -c -o src/test_classe_image-image.obj `if test -f 'src/image.cpp'; then $(CYGPATH_W) 'src/image.cpp'; else $(CYGPATH_W) '$(srcdir)/src/image.cpp'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/test_classe_image-image.Tpo src/$(DEPDIR)/test_classe_image-image.Po
#	$(AM_V_CXX)source='src/image.cpp' object='src/test_classe_image-image.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(test_classe_image_CPPFLAGS) $(CPPFLAGS) $(test_classe_image_CXXFLAGS) $(CXXFLAGS) -c -o src/test_classe_image-image.obj `if test -f 'src/image.cpp'; then $(CYGPATH_W) 'src/image.cpp'; else $(CYGPATH_W) '$(srcdir)/src/image.cpp'; fi`

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-am
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-am

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-am

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) check-am
all-am: Makefile $(PROGRAMS) config.h
installdirs:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-rm -f src/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/$(am__dirstamp)
	-test -z "$(DISTCLEANFILES)" || rm -f $(DISTCLEANFILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
	-test -z "$(BUILT_SOURCES)" || rm -f $(BUILT_SOURCES)
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf src/$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf src/$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS

.MAKE: all check install install-am install-strip

.PHONY: CTAGS GTAGS TAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-cscope clean-generic cscope \
	cscopelist-am ctags ctags-am dist dist-all dist-bzip2 \
	dist-gzip dist-lzip dist-shar dist-tarZ dist-xz dist-zip \
	distcheck distclean distclean-compile distclean-generic \
	distclean-hdr distclean-tags distcleancheck distdir \
	distuninstallcheck dvi dvi-am html html-am info info-am \
	install install-am install-binPROGRAMS install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-man install-pdf install-pdf-am \
	install-ps install-ps-am install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic pdf pdf-am ps ps-am tags tags-am uninstall \
	uninstall-am uninstall-binPROGRAMS


 # ------------- #
 # DOCUMENTATION #
 # ------------- #

# --- #
# MOC #
# --- #

.hh.moc.cpp:
	$(MOC) $(QT_CPPFLAGS) $< -o $@
.h.moc.cpp:
	$(MOC) $(QT_CPPFLAGS) $< -o $@

.hh.moc.cc:
	$(MOC) $(QT_CPPFLAGS) $< -o $@
.h.moc.cc:
	$(MOC) $(QT_CPPFLAGS) $< -o $@

.hh.moc.cxx:
	$(MOC) $(QT_CPPFLAGS) $< -o $@
.h.moc.cxx:
	$(MOC) $(QT_CPPFLAGS) $< -o $@

.hh.moc.C:
	$(MOC) $(QT_CPPFLAGS) $< -o $@
.h.moc.C:
	$(MOC) $(QT_CPPFLAGS) $< -o $@

# --- #
# UIC #
# --- #

.ui.ui.hh:
	$(UIC) $< -o $@

#.ui.ui.h:
#	$(UIC) $< -o $@
%_ui.h: %.ui
	$(UIC) $< -o $@

# --- #
# RCC #
# --- #

.qrc.qrc.cpp:
	$(RCC) -name `echo "$<" | sed 's/\.qrc$$//'` $< -o $@

.qrc.qrc.cc:
	$(RCC) -name `echo "$<" | sed 's/\.qrc$$//'` $< -o $@

.qrc.qrc.cxx:
	$(RCC) -name `echo "$<" | sed 's/\.qrc$$//'` $< -o $@

.qrc.qrc.C:
	$(RCC) -name `echo "$<" | sed 's/\.qrc$$//'` $< -o $@

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
